In [1]:
import numpy as np
import cv2
img = cv2.imread("Flower.png", cv2.IMREAD_UNCHANGED)

In [2]:
# Display the img in the pixel data form
img

array([[[177, 171, 142],
        [180, 174, 145],
        [178, 172, 143],
        ...,
        [183, 177, 154],
        [183, 177, 154],
        [183, 177, 154]],

       [[179, 173, 144],
        [181, 175, 146],
        [179, 173, 144],
        ...,
        [185, 179, 156],
        [186, 180, 157],
        [186, 180, 157]],

       [[179, 173, 144],
        [181, 175, 146],
        [179, 173, 144],
        ...,
        [185, 179, 156],
        [187, 181, 158],
        [187, 181, 158]],

       ...,

       [[166, 154, 118],
        [170, 158, 122],
        [169, 157, 121],
        ...,
        [177, 167, 133],
        [177, 167, 133],
        [177, 167, 133]],

       [[162, 150, 114],
        [165, 153, 117],
        [162, 150, 114],
        ...,
        [178, 168, 134],
        [177, 167, 133],
        [177, 167, 133]],

       [[161, 149, 113],
        [160, 148, 112],
        [154, 142, 106],
        ...,
        [178, 168, 134],
        [178, 168, 134],
        [178, 168, 134]]

In [3]:
# Display the type of image
type(img)

numpy.ndarray

In [4]:
# Graphics industry standard is width by height (width x height)

In [5]:
# Display the len(image)
# len(img) = number of rows
# len(img) = height of an image
len(img)

3507

In [6]:
# Display the len(image[0])
# len(img[0]) = length of a row = number of coloumns
# len(img) = width of an image
len(img[0])

5261

In [7]:
len(img[0][0])

3

In [8]:
img.shape

(3507, 5261, 3)

In [9]:
img.dtype

dtype('uint8')

In [10]:
2**8

256

In [11]:
img[10, 5]

array([179, 174, 143], dtype=uint8)

In [12]:
img[:, :, 0]

array([[177, 180, 178, ..., 183, 183, 183],
       [179, 181, 179, ..., 185, 186, 186],
       [179, 181, 179, ..., 185, 187, 187],
       ...,
       [166, 170, 169, ..., 177, 177, 177],
       [162, 165, 162, ..., 178, 177, 177],
       [161, 160, 154, ..., 178, 178, 178]], dtype=uint8)

In [13]:
img[:, :, 1]

array([[171, 174, 172, ..., 177, 177, 177],
       [173, 175, 173, ..., 179, 180, 180],
       [173, 175, 173, ..., 179, 181, 181],
       ...,
       [154, 158, 157, ..., 167, 167, 167],
       [150, 153, 150, ..., 168, 167, 167],
       [149, 148, 142, ..., 168, 168, 168]], dtype=uint8)

In [14]:
img[:, :, 2]

array([[142, 145, 143, ..., 154, 154, 154],
       [144, 146, 144, ..., 156, 157, 157],
       [144, 146, 144, ..., 156, 158, 158],
       ...,
       [118, 122, 121, ..., 133, 133, 133],
       [114, 117, 114, ..., 134, 133, 133],
       [113, 112, 106, ..., 134, 134, 134]], dtype=uint8)

In [15]:
img.size

55350981

In [16]:
3507*5261*3

55350981